In [1]:
import pybaseball as pb
import pandas as pd

pb.cache.enable()

In [2]:
batting = pb.batting_stats_bref(2025)
print(batting.shape)
batting.head()

(675, 28)

,Name,Age,#days,Lev,Tm,G,PA,AB,R,H,...,SH,SF,GDP,SB,CS,BA,OBP,SLG,OPS,mlbID
1,CJ Abrams,24,214,Maj-NL,Washington,144,635,580,92,149,...,1,3,5,31,3,0.257,0.315,0.433,0.748,682928
2,Wilyer Abreu,26,210,Maj-AL,Boston,116,422,378,53,92,...,1,3,8,6,3,0.243,0.314,0.463,0.777,677800
3,Maximo Acosta,22,228,Maj-NL,Miami,19,61,54,7,11,...,0,0,0,1,2,0.204,0.295,0.389,0.684,691185
4,Luisangel Acu\xc3\xb1a,23,215,Maj-NL,New York,95,193,175,30,41,...,2,1,6,16,1,0.234,0.293,0.274,0.567,682668
5,Ronald Acu\xc3\xb1a Jr.,27,214,Maj-NL,Atlanta,95,412,338,74,98,...,0,0,5,9,1,0.290,0.417,0.518,0.935,660670

In [3]:
print(f"Total players: {batting.shape[0]}")
print(f"Total columns: {batting.shape[1]}")

Total players: 675
Total columns: 28

In [4]:
print(batting.columns.tolist())

['Name', 'Age', '#days', 'Lev', 'Tm', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'BB', 'IBB', 'SO', 'HBP', 'SH', 'SF', 'GDP', 'SB', 'CS', 'BA', 'OBP', 'SLG', 'OPS', 'mlbID']

In [5]:
batting.isnull().sum()

Name     0
Age      0
#days    0
Lev      0
Tm       0
G        0
PA       0
AB       0
R        0
H        0
2B       0
3B       0
HR       0
RBI      0
BB       0
IBB      0
SO       0
HBP      0
SH       0
SF       0
GDP      0
SB       0
CS       0
BA       1
OBP      1
SLG      1
OPS      1
mlbID    0
dtype: int64

In [6]:
batting.to_csv('../data/raw/batting_2024.csv', index=False)
print("Saved")

Saved

In [7]:
import os

os.makedirs('../data/raw', exist_ok=True)
os.makedirs('../data/processed', exist_ok=True)
print("Folders created")

Folders created

In [8]:
batting.to_csv('../data/raw/batting_2024.csv', index=False)
print("Saved")

Saved

In [9]:
batting_2023 = pb.batting_stats_bref(2023)
batting_2023.to_csv('../data/raw/batting_2023.csv', index=False)
print(f"2023 players: {batting_2023.shape[0]}")

2023 players: 660

In [10]:
import sys
sys.path.append('..')

In [11]:
from src.configuration import SCORING

In [12]:
batting["1B"] = batting["H"] - batting["2B"] - batting["3B"] - batting["HR"] #singles not recorded
batting["fantasy_points"] = (
    batting["1B"] * SCORING["single"] +
    batting["2B"] * SCORING["double"] +
    batting["3B"] * SCORING["triple"]+
    batting["HR"] * SCORING["home_run"]+
    batting["BB"] * SCORING["walk"] +
    batting["R"] * SCORING["run"] +
    batting["RBI"] * SCORING["rbi"] +
    batting["SB"] * SCORING["stolen_base"]+
    batting["SO"] * SCORING["strikeout"]
    )

In [13]:
batting[["Name", "1B", "2B", "3B", "HR", "BB", "R", "RBI", "SB", "SO", "fantasy_points"
        ]].sort_values("fantasy_points", ascending=False).head()

,Name,1B,2B,3B,HR,BB,R,RBI,SB,SO,fantasy_points
455,Shohei Ohtani,89,28,10,63,125,159,116,21,210,638
303,Aaron Judge,104,32,2,54,128,142,121,12,165,628
583,Juan Soto,88,20,1,43,127,120,105,38,137,556
492,Cal Raleigh,70,26,0,65,105,118,133,14,205,547
237,Vladimir Guerrero Jr.,131,39,0,31,95,114,99,6,101,546

In [14]:
from pybaseball import statcast
from pybaseball import statcast_batter_expected_stats
savant_batting = statcast_batter_expected_stats(2025)
print(savant_batting.columns.tolist())
savant_batting.head()

['last_name, first_name', 'player_id', 'year', 'pa', 'bip', 'ba', 'est_ba', 'est_ba_minus_ba_diff', 'slg', 'est_slg', 'est_slg_minus_slg_diff', 'woba', 'est_woba', 'est_woba_minus_woba_diff']

,"last_name, first_name",player_id,year,pa,bip,ba,est_ba,est_ba_minus_ba_diff,slg,est_slg,est_slg_minus_slg_diff,woba,est_woba,est_woba_minus_woba_diff
0,"Lindor, Francisco",596019,2025,732,520,0.267,0.260,0.007,0.466,0.454,0.012,0.350,0.345,0.005
1,"Devers, Rafael",646240,2025,729,419,0.252,0.244,0.008,0.479,0.487,-0.008,0.365,0.367,-0.002
2,"Ohtani, Shohei",660271,2025,727,426,0.282,0.274,0.008,0.622,0.649,-0.027,0.418,0.425,-0.007
3,"Schwarber, Kyle",656941,2025,724,408,0.240,0.249,-0.009,0.563,0.581,-0.018,0.391,0.401,-0.010
4,"Olson, Matt",621566,2025,724,453,0.272,0.249,0.023,0.484,0.492,-0.008,0.366,0.360,0.006

In [15]:
import pybaseball
[x for x in dir(pybaseball) if 'stat' in x.lower()]

['batting_stats',
 'batting_stats_bref',
 'batting_stats_range',
 'fielding_stats',
 'league_batting_stats',
 'league_pitching_stats',
 'pitching_stats',
 'pitching_stats_bref',
 'pitching_stats_range',
 'split_stats',
 'statcast',
 'statcast_batter',
 'statcast_batter_exitvelo_barrels',
 'statcast_batter_expected_stats',
 'statcast_batter_percentile_ranks',
 'statcast_batter_pitch_arsenal',
 'statcast_catcher_framing',
 'statcast_catcher_poptime',
 'statcast_fielding',
 'statcast_outfield_catch_prob',
 'statcast_outfield_directional_oaa',
 'statcast_outfielder_jump',
 'statcast_outs_above_average',
 'statcast_pitcher',
 'statcast_pitcher_arsenal_stats',
 'statcast_pitcher_exitvelo_barrels',
 'statcast_pitcher_expected_stats',
 'statcast_pitcher_percentile_ranks',
 'statcast_pitcher_pitch_arsenal',
 'statcast_pitcher_spin_dir_comp',
 'statcast_running',
 'statcast_running_splits',
 'statcast_single_game',
 'statcast_sprint_speed']

In [16]:
savant_batting = pd.read_csv(r"..\data\raw\savant_basic_stats.csv")
print(savant_batting.columns.tolist())
savant_batting.head()

['last_name, first_name', 'player_id', 'year', 'single', 'double', 'triple', 'home_run', 'strikeout', 'walk', 'b_rbi', 'b_total_bases', 'r_total_stolen_base', 'r_run']

,"last_name, first_name",player_id,year,single,double,triple,home_run,strikeout,walk,b_rbi,b_total_bases,r_total_stolen_base,r_run
0,"Devers, Rafael",646240,2025,85,33,0,35,192,112,109,291,1,99
1,"Martin, Austin",668885,2025,34,8,1,1,31,22,7,57,11,22
2,"Díaz, Elias",553869,2025,36,7,0,9,74,21,29,86,0,34
3,"Elko, Tim",671284,2025,4,1,0,4,30,5,8,22,1,6
4,"Paris, Kyren",677347,2025,13,4,1,6,59,10,11,48,7,20

In [17]:
savant_batting["fantasy_points"] = (
    savant_batting["single"] * SCORING["single"] +
    savant_batting["double"] * SCORING["double"] +
    savant_batting["triple"] * SCORING["triple"] +
    savant_batting["home_run"] * SCORING["home_run"] +
    savant_batting["walk"] * SCORING["walk"]+
    savant_batting["b_rbi"] * SCORING["rbi"] +
    savant_batting["r_run"] * SCORING["run"]+
    savant_batting["r_total_stolen_base"] * SCORING["stolen_base"] +
    savant_batting["strikeout"] * SCORING["strikeout"]
        )

In [18]:
savant_batting[["last_name, first_name", "fantasy_points"]
    ].sort_values("fantasy_points", ascending=False).head()

    last_name, first_name  fantasy_points
205          Judge, Aaron             599
151        Ohtani, Shohei             570
235            Soto, Juan             556
534         Ramírez, José             522
54       Perdomo, Geraldo             512

In [20]:
import os
years = [i for i in range(2015, 2026) if i != 2020]
dfs = []

for year in years:
    path = f"../data/raw/savant_batting_{year}.csv"
    df = pd.read_csv(path)
    df["season"] = year
    dfs.append(df)

basic_batting = pd.concat(dfs, ignore_index=True)
print(basic_batting.shape)
basic_batting.head()

(2769, 15)

,"last_name, first_name",player_id,year,hit,single,double,triple,home_run,strikeout,walk,b_rbi,b_total_bases,r_total_stolen_base,r_run,season
0,"Ethier, Andre",444843,2015,116,75,20,7,14,75,43,53,192,2,54,2015
1,"Gyorko, Jedd",576397,2015,104,73,15,0,16,107,27,57,167,0,34,2015
2,"Sogard, Eric",519299,2015,92,76,12,3,1,50,23,37,113,6,40,2015
3,"Tejada, Rubén",514913,2015,94,68,23,0,3,70,38,28,126,2,36,2015
4,"Gennett, Scooter",571697,2015,99,71,18,4,6,68,12,29,143,1,42,2015

In [21]:
basic_batting["season"].value_counts().sort_index()

season
2015    268
2016    268
2017    287
2018    278
2019    273
2021    262
2022    277
2023    293
2024    286
2025    277
Name: count, dtype: int64

In [22]:
basic_batting = basic_batting[basic_batting["season"] != 2020] #remove 2020 season (COVID)
print(basic_batting["season"].value_counts().sort_index())

season
2015    268
2016    268
2017    287
2018    278
2019    273
2021    262
2022    277
2023    293
2024    286
2025    277
Name: count, dtype: int64

In [23]:
basic_batting["fantasy_points"] = (
    basic_batting["single"] * SCORING["single"] +
    basic_batting["double"] * SCORING["double"] +
    basic_batting["triple"] * SCORING["triple"]+
    basic_batting["home_run"]* SCORING["home_run"] +
    basic_batting["walk"] * SCORING["walk"] +
    basic_batting["r_run"] * SCORING["run"] +
    basic_batting["b_rbi"] *SCORING["rbi"] +
    basic_batting["r_total_stolen_base"] *SCORING["stolen_base"] +
    basic_batting["strikeout"] * SCORING["strikeout"]
)

In [24]:
basic_batting[["last_name, first_name", "season", "fantasy_points"]].sort_values("fantasy_points", ascending=False).head(10)

     last_name, first_name  season  fantasy_points
2003     Acuña Jr., Ronald    2023             707
2228        Ohtani, Shohei    2024             653
2416          Judge, Aaron    2024             630
1883          Judge, Aaron    2022             607
1261         Bregman, Alex    2019             603
2636          Judge, Aaron    2025             599
896          Ramírez, José    2018             594
2243       Witt Jr., Bobby    2024             590
532          Betts, Mookie    2016             589
1337       Bellinger, Cody    2019             589

In [25]:
basic_batting = basic_batting.sort_values(["last_name, first_name", "season"])
basic_batting["next_season_points"] = basic_batting.groupby("last_name, first_name")["fantasy_points"].shift(-1) #Points in following season
basic_batting["next_season"] = basic_batting.groupby("last_name, first_name")["season"].shift(-1)

In [32]:
model_data = basic_batting.dropna(subset=["next_season_points"])
print(model_data.shape)

(1963, 18)

In [27]:
model_data[model_data["last_name, first_name"] == "Judge, Aaron"][["last_name, first_name", "season", "fantasy_points", "next_season_points"]]

     last_name, first_name  season  fantasy_points  next_season_points
682           Judge, Aaron    2017             510               292.0
1047          Judge, Aaron    2018             292               260.0
1176          Judge, Aaron    2019             260               409.0
1438          Judge, Aaron    2021             409               607.0
1883          Judge, Aaron    2022             607               340.0
2087          Judge, Aaron    2023             340               630.0
2416          Judge, Aaron    2024             630               599.0

In [31]:
print(model_data.shape)

(1625, 18)

In [29]:
model_data[model_data["last_name, first_name"] == "Judge, Aaron"][["last_name, first_name", "season", "fantasy_points", "next_season_points"]]

     last_name, first_name  season  fantasy_points  next_season_points
682           Judge, Aaron    2017             510               292.0
1047          Judge, Aaron    2018             292               260.0
1438          Judge, Aaron    2021             409               607.0
1883          Judge, Aaron    2022             607               340.0
2087          Judge, Aaron    2023             340               630.0
2416          Judge, Aaron    2024             630               599.0

In [33]:
model_data["season"].value_counts().sort_index()

season
2015    229
2016    223
2017    240
2018    213
2019    191
2021    215
2022    223
2023    230
2024    199
Name: count, dtype: int64